import 'package:flutter/material.dart';

const _hueOffsets = [
  0.0, // primary
  60.0,
  120.0,
  180.0,
  240.0,
  300.0,
  30.0,
  90.0,
  210.0,
  270.0,
];

/// A theme-aware palette for charts.
///
/// Colors are generated by rotating the hue of [ColorScheme.primary] in
/// uniform steps. The result follows the app's brand in both light and dark
/// themes and stays distinct enough for data visualization.
List<Color> chartColorsOf(ColorScheme scheme) {
  final primaryHsl = HSLColor.fromColor(scheme.primary);
  return [
    for (final offset in _hueOffsets)
      primaryHsl.withHue((primaryHsl.hue + offset) % 360.0).toColor(),
  ];
}

/// Returns black or white, whichever contrasts better with [background].
///
/// Use this for text or labels drawn directly on chart slices/bars.
Color foregroundFor(Color background) =>
    ThemeData.estimateBrightnessForColor(background) == Brightness.dark
        ? Colors.white
        : Colors.black;
